### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by WhackyAshu15** [Fexcraft/FVTM#19]
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: net.fexcraft.mod.lib.tmt.ModelRendererTurbo.func_78790_a(FFFIIIF)V

I don't  know why it crashed!!!!!

**Comment by Fexcraft** [comment]
I'd need the crashlog, for sure, the addon packs which you have seem to be outdated / wrong version.

**Comment by WhackyAshu15** [comment]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/20/18 7:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fexcraft Common Library (fcl)
Caused by: java.lang.NoSuchMethodError: net.fexcraft.mod.lib.tmt.ModelRendererTurbo.func_78793_a(FFF)V
	at net.fexcraft.mod.fvtm.model.block.ModelConstructorCenter.<init>(ModelConstructorCenter.java:28)
	at net.fexcraft.mod.fvtm.render.block.ConstructorCenterRenderer.<clinit>(ConstructorCenterRenderer.java:19)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at net.fexcraft.mod.lib.util.registry.RegistryUtil.registerTESRs(RegistryUtil.java:406)
	at net.fexcraft.mod.lib.util.registry.RegistryUtil.prepare(RegistryUtil.java:62)
	at net.fexcraft.mod.lib.FCL.preInit(FCL.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 148929536 bytes (142 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2581 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version      | Source                                          | Signature                                |
	|:----- |:------------------ |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.2       | minecraft.jar                                   | None                                     |
	| UCH   | mcp                | 9.42         | minecraft.jar                                   | None                                     |
	| UCH   | FML                | 8.0.99.99    | forge-1.12.2-14.23.1.2581.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.23.1.2581 | forge-1.12.2-14.23.1.2581.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater  | 1.0          | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCE   | fcl                | XII.42       | Fexcraft Common Library-XII.42.jar              | None                                     |
	| UCH   | flansmod           | 5.5.1        | Flan's Mod-1.12.2-5.5.1.jar                     | None                                     |
	| UCH   | flansmodapocalypse | 1.0          | Flan's Mod-1.12.2-5.5.1.jar                     | None                                     |
	| UCE   | fvtm               | 2.4.b22      | FVTM-1.12.2.jar                                 | None                                     |
	| UCH   | mts                | 10.1.2       | Minecraft+Transport+Simulator-1.12.2-10.1.2.jar | None                                     |

	Loaded coremods (and transformers): 






Thanks for helping man!!!!!!
[2018-08-20-7.log.gz](https://github.com/Fexcraft/FVTM/files/2305838/2018-08-20-7.log.gz)

**Comment by Fexcraft** [comment]
Where you got FVTM from? Latest version is ``2.7.31``.
You got ``2.4.b22`` 🤔 

(latest FVTM will also print installed addon versions in the crash log, for which I hoped to see)

**Comment by WhackyAshu15** [comment]
either fexcraft 9minecraft or mcmod.net
i think it was mc-mod.net

**Comment by Fexcraft** [comment]
Only `minecraft.curseforge.net`, `planetminecraft.com` and `fexcraft.net` are legit/`true` download sources for my mods. 🤔 
http://fexcraft.net/download?modid=fvtm

Those other sites are known as illegal mod reposters.

**Comment by WhackyAshu15** [comment]
oh thanks I shall try it from one of these

**Comment by WhackyAshu15** [comment]
Error: java.lang.NoSuchMethodError: net.fexcraft.mod.lib.tmt.ModelRendererTurbo.func_78790_a(FFFIIIF)V

IT NOW SAYS THIS

**Comment by Fexcraft** [comment]
I aswel need the rest of the log.
Or the addon list, it's after the mod list in the log.

**Comment by WhackyAshu15** [comment]
[crash-2018-08-21_16.09.07-client.txt](https://github.com/Fexcraft/FVTM/files/2305923/crash-2018-08-21_16.09.07-client.txt)
[2018-08-21-2.log.gz](https://github.com/Fexcraft/FVTM/files/2305925/2018-08-21-2.log.gz)

**Comment by Fexcraft** [comment]
Latest version of FVP is ``1.16``, you got ``1.9`` which is no longer compatible.

In case you could have `DiscordApp`, we got a bot with which you can check current addon versions.

**Comment by WhackyAshu15** [comment]
I DON'T HAVE DISCORD

**Comment by WhackyAshu15** [comment]
IN MY file it says I've got
FVP-1.9
GEP-1.6.1
HCP-1.4.1

**Comment by Fexcraft** [comment]
Hmm.
![image](https://user-images.githubusercontent.com/11726534/44397443-a5072900-a540-11e8-99bf-d18c6ea85c63.png)
Are they in the ``addon`` folder?

**Comment by WhackyAshu15** [comment]
YUP

**Comment by WhackyAshu15** [comment]
wait its called addonS
(lower case s, i put emphasis)

**Comment by Fexcraft** [comment]
`FVP 1.9` is outdated though.

**Comment by WhackyAshu15** [comment]
i got it from your website

**Comment by Fexcraft** [comment]
Then do get the newer version off the site.

**Comment by WhackyAshu15** [comment]
i just did that
is anything else outdated?

**Comment by Fexcraft** [comment]
just FVP was wrong it seems.

**Comment by WhackyAshu15** [comment]
wait it shows the latest version is 1.9 
i'l check again 1 minute

**Comment by WhackyAshu15** [comment]
oh i found it 
i thought latest versions were at the bottom!!!
It was in the middle.
i will download it now

**Comment by Fexcraft** [comment]
The site doesn't sort it as expected right now, do not know when it will be fixed.
`>.>`

**Comment by WhackyAshu15** [comment]
kk :]

**Comment by WhackyAshu15** [comment]
It worked!!!!!!
Thanks man,
 You have made a great mod,
KEEP UP THE GOOD WORK!!!!! 👍 🥇

**Comment by WhackyAshu15** [comment]
3RD LINE:
* YOU have made a great mod,

**Comment by Fexcraft** [comment]
![image](https://user-images.githubusercontent.com/11726534/44398018-a20d3800-a542-11e8-95f5-d26da92b43da.png)
- - - -
So I guess the issue can be closed?

**Comment by WhackyAshu15** [comment]
kk
but you get the idea

**Comment by WhackyAshu15** [comment]
should i close issue?????

**Comment by Fexcraft** [comment]
The website should "sort" downloads now based on when they were added.

**Comment by WhackyAshu15** [comment]
Hey btw how do you connect the t2 to a trailer?

**Comment by Fexcraft** [comment]
Either, right-click with a trailer item the T2,
or do like on one video, the key used should be in controls menu.
