### ISSUE TITLE
Crash ( unknown cause )

### ISSUE THREAD

**Issue by Mrleplayz** [Fexcraft/FVTM#21]
---- Minecraft Crash Report ----
// Sorry :(

Time: 9/8/18 8:23 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.fexcraft.mod.fvtm.util.Resources.regAddons(Resources.java:187)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_Resources_regAddons_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:762)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fexcraft.mod.fvtm.util.Resources.regAddons(Resources.java:187)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_Resources_regAddons_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:762)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 69762136 bytes (66 MB) / 315371520 bytes (300 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                             | Signature                                |
	|:----- |:--------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| UCH   | minecraft | 1.12.2       | minecraft.jar                      | None                                     |
	| UCH   | mcp       | 9.42         | minecraft.jar                      | None                                     |
	| UCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.4.2739.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge     | 14.23.4.2739 | forge-1.12.2-14.23.4.2739.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | fcl       | XII.43       | Fexcraft+Common+Library-XII.43.jar | None                                     |
	| UCH   | fmr       | 1.0          | Fexcraft+Common+Library-XII.43.jar | None                                     |
	| UCH   | fvtm      | 2.7.32       | FVTM-2.7.32-1.12.x.jar             | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13521 Compatibility Profile Context 24.20.11016.4' Renderer: 'AMD Radeon (TM) R7 360 Series'
	
	FVTM Addons: 

	Launched Version: 1.12.2-forge1.12.2-14.23.4.2739
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R7 360 Series GL version 4.5.13521 Compatibility Profile Context 24.20.11016.4, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Custom Pack
	Current Language: English (English)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Athlon(tm) X4 845 Quad Core Processor

**Comment by Fexcraft** [comment]
That error a few people reported on discord, I sent a fixed file, but noone told me if it works, so I didn't push an update.
Here though, https://cdn.discordapp.com/attachments/365125356660719638/486072454301614080/FVTM-2.7.32-1.12.x.jar
If it works, the fix will be next official release.

**Comment by Mrleplayz** [comment]
The fix does indeed work.

sub, 8. ruj 2018. u 09:00 Fexcraft <notifications@github.com> napisao je:

**Comment by ExDomino** [comment]
The fix allows me to start the game, but I can't use the mod in creative in order to test because the creative tabs are crashing the game. And a lot of blocks and items have no texture.

**Comment by Fexcraft** [comment]
@ExDomino see #24

**Comment by Fexcraft** [comment]
Should be fixed in 2.8.33
